[pytest]
testpaths =
    aicybops-lib/tests
    aicybops_models/tests
python_files = test_*.py
addopts = -v -ra -q
log_cli = true
log_cli_level = INFO
pythonpath = 
    .
    aicybops-lib
norecursedirs = 
    **/test_sklearn_model.py