# Training defaults
LEARNING_RATE = 0.0001
BATCH_SIZE = 32
TRAIN_RATIO = 0.8
VAL_RATIO = 0.2

# Model architecture defaults
LSTM_HIDDEN_DIM = 32
WINDOW_SIZE = 10
STRIDE = 1
ALIGN_FREQ = '1s'

# Anomaly detection defaults
RISK_LEVEL = 1e-3
DEPTH = 10
SPOT_TYPE = 'dSPOT'
INIT_QUANTILE = 0.95

# Early stopping defaults
EARLY_STOPPING_PATIENCE = 5
EARLY_STOPPING_MIN_DELTA = 0.001

DAM_DEFAULTS = {
    'LEARNING_RATE': LEARNING_RATE,
    'BATCH_SIZE': BATCH_SIZE,
    'TRAIN_RATIO': TRAIN_RATIO,
    'VAL_RATIO': VAL_RATIO,
    'LSTM_HIDDEN_DIM': LSTM_HIDDEN_DIM,
    'WINDOW_SIZE': WINDOW_SIZE,
    'STRIDE': STRIDE,
    'ALIGN_FREQ': ALIGN_FREQ,
    'RISK_LEVEL': RISK_LEVEL,
    'DEPTH': DEPTH,
    'SPOT_TYPE': SPOT_TYPE,
    'INIT_QUANTILE': INIT_QUANTILE,
    'EARLY_STOPPING_PATIENCE': EARLY_STOPPING_PATIENCE,
    'EARLY_STOPPING_MIN_DELTA': EARLY_STOPPING_MIN_DELTA,
}
